<xml>
	<ToUserName><![CDATA[${toUser}]]></ToUserName>
	<FromUserName><![CDATA[${fromUser}]]></FromUserName>
	<CreateTime>${createTime}</CreateTime>
	<MsgType><![CDATA[location]]></MsgType>
	<Location_X>${locationX}</Location_X>
	<Location_Y>${locationY}</Location_Y>
	<Scale>${scale}</Scale>
	<Label><![CDATA[${label!'位置信息'}]]></Label>
	<MsgId>${msgId}</MsgId>
</xml> 