<xml>
	<ToUserName><![CDATA[${toUser}]]></ToUserName>
 	<FromUserName><![CDATA[${fromUser}]]></FromUserName> 
 	<CreateTime>${createTime}</CreateTime>
	<MsgType><![CDATA[link]]></MsgType>
	<Title><![CDATA[${title!'公众平台官网链接'}]]></Title>
	<Description><![CDATA[${description!'公众平台官网链接'}]]></Description>
	<Url><![CDATA[${url}]]></Url>
	<MsgId>${msgId}</MsgId>
</xml> 